### ISSUE TITLE
User not being prompted to confirm project type on bind

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind-vscode#49] opened 2019-06-21 15:09 UTC
**Environment:**
codewind-vscode checked out at `master 43eebf0`

**Describe the bug:**
When importing a project you are not prompted to confirm what type of project (liberty, java, nodejs, swift, docker) it should be treated as. Once imported there is no way to change the project type.

**To Reproduce:**
Import an existing project, you will not be prompted to confirm what type it is. For example if you import a Node.js project with a package.json it will be imported as a Node.js project and you will not have the chance to chose to import it as a plain docker project.

This is probably related to #26 and #32.

**Comment by tetchel** [comment] 2019-06-21 17:58
i can't reproduce this with the same HEAD
![image](https://user-images.githubusercontent.com/8888438/59941968-8e658300-942c-11e9-8ce0-362171905766.png)

**Comment by tetchel** [comment] 2019-06-21 20:42
sorry howard not sure what happened for you, unless something was different in your portal
![image](https://user-images.githubusercontent.com/8888438/59950302-8e24b200-9443-11e9-86ba-84d3fff2efb3.png)

**Comment by jopit** [comment] 2019-06-24 14:49
I'm going to close this; @hhellyer if you can reproduce, please reopen.

**Closed by jopit** 2019-06-24 14:49 UTC
Labels: bug
